# ============================================================
# pyproject.toml (Python project configuration)
# ============================================================
# REQ.PYTHON: Python projects MUST include pyproject.toml as the single source of truth.
# WHY: Centralizes project configuration.
# Python is used for Zensical documentation generation and development tooling,
# even though the project itself is not a Python package.

[project]
name = "applied-computing-foundations"
readme = "README.md"
requires-python = ">=3.14"
version = "0.2.0"

# CUSTOM: Project metadata.
authors = [{ name = "Denise Case", email = "dcase@nwmissouri.edu" }]
description = "Documentation for computing foundations."
keywords = ["applied computing", "foundations", "education", "analytics"]
license-files = ["LICENSE"]

# REQ.DEPS: Keep runtime dependencies minimal.
# OBS: This toolkit uses only the Python standard library.
dependencies = []

[project.optional-dependencies]
dev = [
    # REQ.DEV.DEPS: External packages used for linting, testing, type checking, etc.
    "pre-commit",
    "validate-pyproject",
]
docs = [
    # REQ.DOCS.DEPS: External packages used to generate project documentation.
    "mkdocstrings[python]",
    "zensical",
]

[project.urls]
"Home" = "https://denisecase.github.io/applied-computing-foundations/"
"Repo" = "https://github.com/denisecase/applied-computing-foundations"
"Issues" = "https://github.com/denisecase/applied-computing-foundations/issues"

[tool.uv]
package = false # REQ.UV: Disable universal versioning for non-packages.
# WHY: This project is not intended to be distributed as a package.
